[package]
    name="cedar-py"
    version="0.1.0"
    edition="2021"

[lib]
    name="_cedar_py"
    crate-type=["cdylib"]

[dependencies]
    pyo3={ version="0.22", features=["extension-module", "anyhow"] }
    cedar-policy="4.8"
    serde_json="1.0"
    anyhow="1.0"
